server:
  port: 8080
  servlet:
    context-path: /musala
spring:
  datasource:
    username: admin
    password:
    url: jdbc:h2:mem:testdb;DATABASE_TO_LOWER=TRUE
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    open-in-view: false